# Generated by Django 3.1.4 on 2021-07-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='u_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='u_name',
            new_name='name',
        ),
    ]
